### ISSUE TITLE
License missing from gemspec

### ISSUE THREAD

**Issue by bf4** [austenito/ruby-resty#11]

**Comment by austenito** [comment]
Added MIT licensing. Thanks :flags:

**Comment by bf4** [comment]
Thanks! How did you make that flag?

**Comment by austenito** [comment]
":flag:" without the quotes

I find this to be very useful in my day-to-day activities hehe http://www.emoji-cheat-sheet.com/

**Comment by bf4** [comment]
lifehack +1 thanks
