### ISSUE TITLE
quick question about resty 

### ISSUE THREAD

**Issue by ghost** [austenito/ruby-resty#13]
hey
i'm curious if you wanted "resty" to be a console that could evaluate ruby and be shipped with all of Pry's commands, or if you wanted to build the console with your own language? (or commands, in Pry language)

pry has something called "command sets" that you've probably come across. the idea behind them was to support the person who wanted to build their own console(with its commands or its own language). unfortunately the idea wasn't expanded on that much, but im curious how getting that support from pry would have changed how you implemented resty.

thanks!

**Comment by ghost** [comment]
sorry, i wasn't that clear about command sets. you can create your own, add the resty commands or language to it, and set pry to use that command set whenever it looks up a command. the default command set includes all of prys commands, but you can replace that command set with your own.

**Comment by austenito** [comment]
Hey Rob - I originally didn't want it to have all of Pry's commands. I sway back and forth between hiding default Pry commands and allowing the user use all the things that Pry has to offer. Since Ruby developers are using this tool and probably have some familiarity with Pry, I decided to go with exposing everything to them.

**Comment by ghost** [comment]
that makes sense. 
pry has made small progress on command sets & mix-match of commands.
it's theoretically possible that pry could have a command set for commands defined inside ~/.pryrc, navigation commands(cd/ls), or introspection commands(show-doc, show-source) that could be easily loaded/unloaded at runtime to customize what commands a console has.  the concept has been neglected in pry, but i am thinking about enhancing and bringing it back alive. I was curious what you were looking for, and why/what decisions you made.

pry(& its command set/command API) could become `pry-core` and be shipped with no commands. `pry-commands` might be the gem that implements the commands you know in pry already. 
there's a lot of potential to support modularization and customization for pry to moprh into more a REPL and become a console that you could even implement domain languages on (esp with the regexp commands).

thanks again for the insight
