### ISSUE TITLE
Add JSON formatting options from jq

### ISSUE THREAD

**Issue by austenito** [austenito/ruby-resty#5]
@tpitale requests support for JQ options to format the JSON output:

http://stedolan.github.io/jq/

**Comment by austenito** [comment]
Turns out Pry can call out to your shell:

```
resty> GET /api/foo
resty> .echo '#{JSON.dump(response)}' | jq '.'`
```

That's pretty powerful. If we can collect the jq arguments in a command option, https://github.com/pry/pry/wiki/Custom-commands then we can pipe the string to the shell and get the formatted output in one line.

**Comment by tpitale** [comment]
Hell yeah. Pry is amazeballs.

**Comment by austenito** [comment]
I started playing around with adding JQ type filtering, but I don't think we something as expressive as JQ. People using the repl can interact with the response as a ruby hash, which is easier IMHO.
